/**
 * 
 */
package ch.zhaw.swengineering.event;

import java.util.EventListener;

/**
 * @author Daniel Brun
 *
 * Listener interface for events generated by the view.
 */
public interface ViewEventListener extends EventListener {
	/**
	 * Called when the user entered a parking lot number.
	 *
	 * @param parkingLotEnteredEvent Event data
	 */
	void parkingLotEntered(ParkingLotEnteredEvent parkingLotEnteredEvent);
}
