/**
 * 
 */
package ch.zhaw.swengineering.event;

import java.util.EventListener;

/**
 * @author Daniel Brun
 *
 * Listener interface for events generated by the view.
 */
public interface ViewEventListener extends EventListener {

	/**
	 * Calles when an input was entered in the view.
	 * 
	 * @param anInputEvent The input event.
	 */
	void inputEntered(ViewInputEvent anInputEvent);
}
